# Generated by Django 4.0.4 on 2022-05-11 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_delete_diak_feladat_egyezzik_alter_feladat_kie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feladat',
            name='egyezzik',
        ),
    ]
